### ISSUE TITLE
Broken in every non-SBCL lisp

### ISSUE THREAD

**Issue by Devon7** [AccelerationNet/a-cl-logger#4]
Abandonware?

Bug fixable by years-old pull request https://github.com/marvinkohl/a-cl-logger/tree/ecl-support

Another fix would put `#+SBCL`
in front of the broken code
```
            (push (lambda ()
                    (ignore-errors (force-output f))
                    (ignore-errors (close f)))
                  sb-ext:*exit-hooks*)
```

or delete it altogether since SBCL, CCL and no doubt most lisps
already go to some trouble on exit to cleanly close open streams.

**Comment by Devon7** [comment]
```
;; Workaround
(defpackage #:sb-ext
  (:export #:*exit-hooks*))
(defvar sb-ext:*exit-hooks* '() "Workaround A-CL-LOGGER bug.")
(ql:quickload '#:a-cl-logger)
```

**Comment by bobbysmith007** [comment]
Hopefully this is fixed now
Sorry it took so long to merge the original pull request. I apparently missed the original request, and I haven't gotten to use common lisp in multiple years. 

This project is up for adoption if anyone wants to maintain it.
